version: '3.9'
services:
  binduLogic-database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: binduLogic-ticket-dispenser